spring.datasource.url=jdbc:mysql://metro.proxy.rlwy.net:49692/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=duIqweMFQyDwVAhczMcaLpNTRZSByNqr

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.thymeleaf.cache=false

server.port=${PORT:8080}